Card component
hayden-93/frontend-practice pull request #1
Opened 2022-01-19 17:01 UTC by hayden-93

- Added the Card Component into the UI
- Created the Card Component in the `components` directory
- Installed the `react-feather` icons library
- Added a custom token in `tailwind.config`
- Created a `public` directory which contains all images

2022-01-19 20:11 UTC, aron-bs requested changes

2022-01-19 20:11 UTC, aron-bs commented on src/App.tsx
> +import { Card, Avatar } from "./components/Card/Card";
Import `Avatar` from Card?

2022-01-19 20:11 UTC, aron-bs commented on src/App.tsx
> +      <div className="max-w-screen-mobile mx-auto font-sans py-16">
Could potentially create a new component such as `Layout` here (Suggestion, not required)

2022-01-19 20:11 UTC, aron-bs commented on src/App.tsx
> +            <img src="/equilibrium.jpg" alt="Equilibrium Logo" className="rounded-2xl" />
Could extend this to make use of composition (Think compound components)

2022-01-19 20:11 UTC, aron-bs commented on src/App.tsx
> +            <h3 className="text-white text-2xl font-bold">Equilibrium #3429</h3>
Same for these elements within the `Card` component

2022-01-19 20:11 UTC, aron-bs commented on src/App.tsx
> +        <Card className="bg-neutral-card-dark-blue mx-auto p-8 rounded-2xl">
Is the `className` needed here? Are these styles overrides for this Card instance or should they be applied as base classes for all Card instances?

2022-01-19 20:11 UTC, aron-bs commented on src/components/Card/Card.tsx
> +  const classes = ["", className].join(" ").trim();
Previous comment about base classes - Could they be applied here instead if you know they will be used for all Card instances?

2022-01-19 20:11 UTC, aron-bs commented on src/components/Card/Card.tsx
> +  const classes = ["", className].join(" ").trim();
Same as class mention above

2022-01-19 20:11 UTC, aron-bs commented on src/components/Card/Card.tsx
> +  const classes = ["", className].join(" ").trim();
Same as class mention above

2022-01-20 10:58 UTC, hayden-93 commented on src/App.tsx
> +import { Card, Avatar } from "./components/Card/Card";
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/e755f5da4b056d53394446220cf3d5041e00e1d6

2022-01-20 10:59 UTC, hayden-93 commented on src/App.tsx
> +      <div className="max-w-screen-mobile mx-auto font-sans py-16">
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/e755f5da4b056d53394446220cf3d5041e00e1d6

2022-01-20 11:57 UTC, hayden-93 commented on src/App.tsx
> +            <img src="/equilibrium.jpg" alt="Equilibrium Logo" className="rounded-2xl" />
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/f90b654b54145cbb511b6c3fa1a63c8524b44cea

2022-01-20 11:57 UTC, hayden-93 commented on src/App.tsx
> +            <h3 className="text-white text-2xl font-bold">Equilibrium #3429</h3>
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/f90b654b54145cbb511b6c3fa1a63c8524b44cea

2022-01-20 11:57 UTC, hayden-93 commented on src/App.tsx
> +        <Card className="bg-neutral-card-dark-blue mx-auto p-8 rounded-2xl">
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/f90b654b54145cbb511b6c3fa1a63c8524b44cea

2022-01-20 11:57 UTC, hayden-93 commented on src/components/Card/Card.tsx
> +  const classes = ["", className].join(" ").trim();
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/f90b654b54145cbb511b6c3fa1a63c8524b44cea

2022-01-20 11:57 UTC, hayden-93 commented on src/components/Card/Card.tsx
> +  const classes = ["", className].join(" ").trim();
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/f90b654b54145cbb511b6c3fa1a63c8524b44cea

2022-01-20 11:57 UTC, hayden-93 commented on src/components/Card/Card.tsx
> +  const classes = ["", className].join(" ").trim();
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/f90b654b54145cbb511b6c3fa1a63c8524b44cea

2022-01-20 12:34 UTC, aron-bs requested changes
Good progress, just a few more mentions for you to consider

2022-01-20 12:34 UTC, aron-bs commented on src/App.tsx
> +      <Layout>
I would include this div as part of your `<Layout />` component

2022-01-20 12:34 UTC, aron-bs commented on src/App.tsx
> +          <div className="mt-6 space-y-3">
Could you create a new component to contain the card's content?

2022-01-20 12:34 UTC, aron-bs commented on src/App.tsx
> +              </div>
Will all card prices contain this code block? If so, why don't you include this as part of `CardPrice`?

2022-01-20 12:34 UTC, aron-bs commented on src/App.tsx
> +              </div>
Will each card deadline contain this code block? If so, why don't you include this as part of `CardDeadline`?

2022-01-20 12:34 UTC, aron-bs commented on src/App.tsx
> +          <CardSeperator />
Will `CardSeparator` only ever be used within a `Card`? Or could this be a reusable component that you can apply class overrides to for use within a `Card`?

2022-01-20 12:34 UTC, aron-bs commented on src/App.tsx
> +            </CardProfileName>
Could `CardProfileName`'s nested elements be added to the component itself? If they were then you will only be required to add the copy as this components children

2022-01-20 12:41 UTC, hayden-93 commented on src/App.tsx
> +      <Layout>
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/66adf025cdaa472bae10c086aed95c7ed3e44263

2022-01-20 12:48 UTC, hayden-93 commented on src/App.tsx
> +          <div className="mt-6 space-y-3">
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/be37f586334c95f6072e8c4cf2a1174584cfe04a

2022-01-20 13:00 UTC, hayden-93 commented on src/App.tsx
> +              </div>
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/c405cf6c9276c0442c9e1198dcd7d2a5d95be145

2022-01-20 13:04 UTC, hayden-93 commented on src/App.tsx
> +              </div>
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/2b16038c36aabf50ce5892ffbf288ba1e37f3e39

2022-01-20 13:08 UTC, hayden-93 commented on src/App.tsx
> +          <CardSeperator />
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/0a2f949fa7a80f65829e3914837375b064b61b81

2022-01-20 13:13 UTC, hayden-93 commented on src/App.tsx
> +            </CardProfileName>
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/eddb6a45ae45713a7a0d4a81b674931b7fc475fc

2022-01-20 13:19 UTC, aron-bs commented on src/App.tsx
> +          <CardSeperator />
You have moved `CardSeparator` into `Card.tsx` which is right but this could also be abstracted into its own reusable component, named `Separator` - Then your `CardSeparator` component would make use of `Separator`, applying class overrides to align it to the card (If your Card separator needs to be styled a specific way)

2022-01-20 13:25 UTC, hayden-93 commented on src/App.tsx
> +          <CardSeperator />
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/b3f38f31d219945a270758252a45710c2127d704

2022-01-20 13:25 UTC, aron-bs requested changes

2022-01-20 13:25 UTC, aron-bs commented on src/App.tsx
> +          <CardProfileName>Created by </CardProfileName>
Should this contain the person's name instead?

2022-01-20 13:25 UTC, aron-bs commented on src/components/Card/Card.tsx
> +    </p>
This contains a hard coded text value "Hayden Buckley-Smith" - Ask yourself the question:

"Do I want every Card instance to render "Hayden Buckley-Smith?"

If you don't then this should be rendered as the components children

2022-01-20 13:36 UTC, hayden-93 commented on src/App.tsx
> +          <CardProfileName>Created by </CardProfileName>
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/c614c94efb39027d1860749083563b6ee24ec081

2022-01-20 13:38 UTC, hayden-93 commented on src/components/Card/Card.tsx
> +    </p>
Done https://github.com/hayden-93/frontend-practice/commit/c614c94efb39027d1860749083563b6ee24ec081

2022-01-20 13:45 UTC, aron-bs requested changes

2022-01-20 13:45 UTC, aron-bs commented on src/App.tsx
> +import { Layout } from "./components/Layout/Layout";
At the moment you are importing files from multiple sources. You can reduce the need for multiple imports by creating a single source for all of your exports - Looking at your import paths, where do you think this file should live?

2022-01-20 13:45 UTC, aron-bs commented on src/components/Layout/Layout.tsx
> +import { ReactNode } from "react";
```suggestion
import type { ReactNode } from "react";
```

2022-01-20 14:00 UTC, hayden-93 commented on src/App.tsx
> +import { Layout } from "./components/Layout/Layout";
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/d77b580e9a3176b24e99665afcd089742a4ff2b4

2022-01-20 14:05 UTC, hayden-93 commented on src/App.tsx
> +import "./index.css";
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/91046796f7610135effaff06b86426c6d045892a

2022-01-20 14:07 UTC, hayden-93 commented on src/components/Layout/Layout.tsx
> +import { ReactNode } from "react";
Done https://github.com/hayden-93/frontend-practice/pull/1/commits/2c1d624d1f1a4e17e81c087654fbb38ee6dd40d6

2022-01-20 14:21 UTC, aron-bs requested changes

2022-01-20 14:21 UTC, aron-bs commented on src/App.tsx
>    return (
Looks good, but the card data is currently hard coded. Let's pull this data in from an external source instead.

Take a look at the following to get an idea of how you would create a mock server that you can send HTTP requests to mock how you would interact with a real world API:

- [JSON Server](https://github.com/typicode/json-server)
- [Mirage](https://miragejs.com/)
- [MSW](https://mswjs.io/)

2022-01-21 13:55 UTC, hayden-93 commented on src/App.tsx
>    return (
Looked at these and went for MSW. This was my favourite, only issue was importing a CommonJS module. This was resolved through using the following plugin `@originjs/vite-plugin-commonjs`

2022-01-21 15:33 UTC, aron-bs approved these changes
🥇

2022-01-21 15:33 UTC, merged